// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: petservice/pet_service.proto

package petstore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Species string `protobuf:"bytes,2,opt,name=species,proto3" json:"species,omitempty"`
}

func (x *Pet) Reset() {
	*x = Pet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petservice_pet_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_petservice_pet_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_petservice_pet_service_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pet) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

type Pets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pets []*Pet `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
}

func (x *Pets) Reset() {
	*x = Pets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petservice_pet_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pets) ProtoMessage() {}

func (x *Pets) ProtoReflect() protoreflect.Message {
	mi := &file_petservice_pet_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pets.ProtoReflect.Descriptor instead.
func (*Pets) Descriptor() ([]byte, []int) {
	return file_petservice_pet_service_proto_rawDescGZIP(), []int{1}
}

func (x *Pets) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type PetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PetRequest) Reset() {
	*x = PetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petservice_pet_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRequest) ProtoMessage() {}

func (x *PetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petservice_pet_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRequest.ProtoReflect.Descriptor instead.
func (*PetRequest) Descriptor() ([]byte, []int) {
	return file_petservice_pet_service_proto_rawDescGZIP(), []int{2}
}

var File_petservice_pet_service_proto protoreflect.FileDescriptor

var file_petservice_pet_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x65, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33,
	0x0a, 0x03, 0x50, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x04, 0x50, 0x65, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x04, 0x70,
	0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x50, 0x65, 0x74, 0x52,
	0x04, 0x70, 0x65, 0x74, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x32, 0x2d, 0x0a, 0x0a, 0x50, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x1f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x73, 0x12, 0x0b, 0x2e, 0x50,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x05, 0x2e, 0x50, 0x65, 0x74, 0x73,
	0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x6c, 0x61, 0x79, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_petservice_pet_service_proto_rawDescOnce sync.Once
	file_petservice_pet_service_proto_rawDescData = file_petservice_pet_service_proto_rawDesc
)

func file_petservice_pet_service_proto_rawDescGZIP() []byte {
	file_petservice_pet_service_proto_rawDescOnce.Do(func() {
		file_petservice_pet_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_petservice_pet_service_proto_rawDescData)
	})
	return file_petservice_pet_service_proto_rawDescData
}

var file_petservice_pet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_petservice_pet_service_proto_goTypes = []interface{}{
	(*Pet)(nil),        // 0: Pet
	(*Pets)(nil),       // 1: Pets
	(*PetRequest)(nil), // 2: PetRequest
}
var file_petservice_pet_service_proto_depIdxs = []int32{
	0, // 0: Pets.pets:type_name -> Pet
	2, // 1: PetService.GetPets:input_type -> PetRequest
	1, // 2: PetService.GetPets:output_type -> Pets
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_petservice_pet_service_proto_init() }
func file_petservice_pet_service_proto_init() {
	if File_petservice_pet_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_petservice_pet_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petservice_pet_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petservice_pet_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_petservice_pet_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_petservice_pet_service_proto_goTypes,
		DependencyIndexes: file_petservice_pet_service_proto_depIdxs,
		MessageInfos:      file_petservice_pet_service_proto_msgTypes,
	}.Build()
	File_petservice_pet_service_proto = out.File
	file_petservice_pet_service_proto_rawDesc = nil
	file_petservice_pet_service_proto_goTypes = nil
	file_petservice_pet_service_proto_depIdxs = nil
}
